In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
import scipy
import scipy.stats as stats

QUESTION - 21

In [39]:
np.random.seed(0)
age_groups = np.random.choice(['18-30', '31-50', '51+', '51+'], size=30)
voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=30)
voter_preferences


array(['Candidate B', 'Candidate A', 'Candidate B', 'Candidate A',
       'Candidate B', 'Candidate B', 'Candidate A', 'Candidate B',
       'Candidate B', 'Candidate A', 'Candidate A', 'Candidate B',
       'Candidate A', 'Candidate B', 'Candidate B', 'Candidate B',
       'Candidate B', 'Candidate B', 'Candidate A', 'Candidate B',
       'Candidate A', 'Candidate B', 'Candidate B', 'Candidate B',
       'Candidate B', 'Candidate A', 'Candidate B', 'Candidate A',
       'Candidate A', 'Candidate B'], dtype='<U11')

In [40]:
data_table = pd.crosstab(age_groups,voter_preferences)
data_table

col_0  Candidate A  Candidate B
row_0                          
18-30            2            6
31-50            4            4
51+              5            9

In [41]:
observed_values = data_table.values
observed_values

array([[2, 6],
       [4, 4],
       [5, 9]], dtype=int64)

In [42]:
stats_test ,p,dof,excepted_value = stats.chi2_contingency(observed_values)
excepted_value

array([[2.93333333, 5.06666667],
       [2.93333333, 5.06666667],
       [5.13333333, 8.86666667]])

In [43]:
dof = (3-1)*(2-1)

In [44]:
from scipy.stats import chi2

In [45]:
for i in zip(observed_values,excepted_value):
    print(i)

(array([2, 6], dtype=int64), array([2.93333333, 5.06666667]))
(array([4, 4], dtype=int64), array([2.93333333, 5.06666667]))
(array([5, 9], dtype=int64), array([5.13333333, 8.86666667]))


In [46]:
chisquare_test = sum([(o-e)**2 /e for o,e in zip(observed_values,excepted_value)])

In [47]:
chisquare_test

array([0.68831169, 0.39849624])

In [48]:
chisquare_stats = chisquare_test.sum()

In [49]:
chisquare_stats

1.0868079289131922

In [50]:
alpha = 0.05

In [51]:
chi2_critical  = chi2.ppf(1-alpha,df = dof)
chi2_critical

5.991464547107979

In [52]:
if chisquare_stats >= chi2_critical:
    print("reject the null hypothesis, there is a relationship between two categorical variable")
else:
    print("fail to reject null hypothesis, no relationship")

fail to reject null hypothesis, no relationship


QUESTION - 22

In [53]:
data = np.array([[50, 30, 40, 20], [30, 40, 30, 50], [20, 30, 40, 30]])

In [54]:
data_frame =pd.DataFrame(data,columns=['EAST','WEST','NORTH','SOUTH'])

In [55]:
observed_values = data_frame.values
observed_values

array([[50, 30, 40, 20],
       [30, 40, 30, 50],
       [20, 30, 40, 30]])

In [56]:
stats_test,p,dof,excepted_values = stats.chi2_contingency(data_frame)

In [60]:
excepted_values

array([[34.14634146, 34.14634146, 37.56097561, 34.14634146],
       [36.58536585, 36.58536585, 40.24390244, 36.58536585],
       [29.26829268, 29.26829268, 32.19512195, 29.26829268]])

In [58]:
dof = (3-1)*(4-1)

In [62]:
for i in zip(observed_values,excepted_values):
    print(i)

(array([50, 30, 40, 20]), array([34.14634146, 34.14634146, 37.56097561, 34.14634146]))
(array([30, 40, 30, 50]), array([36.58536585, 36.58536585, 40.24390244, 36.58536585]))
(array([20, 30, 40, 30]), array([29.26829268, 29.26829268, 32.19512195, 29.26829268]))


In [64]:
chisquare_test = sum([(o-e)**2 / e for o, e in zip(observed_values, excepted_values)])

In [66]:
chisquare_stats = chisquare_test.sum()

In [67]:
alpha = 0.05

In [68]:
chi2_critical = chi2.ppf(1-alpha, df = dof)

In [69]:
chi2_critical

12.591587243743977

In [70]:
if chisquare_stats >= chi2_critical:
    print("reject the null hypothesis, there is a relationship between two categorical variable")
else:
    print("fail to reject null hypothesis, no relationship")

reject the null hypothesis, there is a relationship between two categorical variable


QUESTION - 23

In [72]:
data = np.array([[50, 30, 20], [30, 40, 30], [20, 30, 40]])

In [74]:
data_frame = pd.DataFrame(data)
data_frame

0   1   2
0  50  30  20
1  30  40  30
2  20  30  40

In [76]:
observed_values = data_frame.values
observed_values

array([[50, 30, 20],
       [30, 40, 30],
       [20, 30, 40]])

In [80]:
stats_test, p, dof, expected_values = stats.chi2_contingency(observed_values)
expected_values

array([[34.48275862, 34.48275862, 31.03448276],
       [34.48275862, 34.48275862, 31.03448276],
       [31.03448276, 31.03448276, 27.93103448]])

In [81]:
dof = (3-1)*(3-1)

In [85]:
chisquare_test = sum([(o-e)**2 / e for o, e in zip(observed_values, expected_values)])
chisquare_test

array([11.48888889,  1.5       ,  9.17283951])

In [83]:
chisquare_stats = chisquare_test.sum()

In [84]:
chisquare_stats

22.16172839506173

In [86]:
alpha = 0.05

In [88]:
chi2_critical = chi2.ppf(1-alpha, df = dof)
chi2_critical

9.487729036781154

In [89]:
if chisquare_stats >= chi2_critical:
    print("reject the null hypothesis, there is a relationship between two categorical variable")
else:
    print("fail to reject null hypothesis, no relationship")

reject the null hypothesis, there is a relationship between two categorical variable


QUESTION - 24

In [90]:
standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]
premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]
deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

In [91]:
fstats, pvalue = stats.f_oneway(standard_scores,premium_scores,deluxe_scores)

In [92]:
if pvalue <= 0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject null hypothesis")

Reject the null hypothesis
